import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

const Hobbi = () => {
  return (
    <>
      <Head>
        <title>My hobbies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/profile.png" />
      </Head>
      <div className="hobby">
        <div className="hobby_nav">
          <Link href={"/"} ><h1>Saidolim Bakhodirov</h1></Link>
          <div className="h_nav_right">
            <Link href={"/Skill"} ><p>My skills</p></Link>
            <Link href={"/About"} ><p>About </p></Link>
          </div>
        </div>
        <div className="hobby_top">
          <h1>Here can be found my hobbies</h1>
          <h3>I have a lot of hobbies and skills <br />
            i`m interested in learning new things <br />
            and i find that you will get FUN <br /> |see below| </h3>
        </div>
        <div className="hobby_bottom">


        </div>
      </div>

      <div className="hobbi_cards">
        <div className="cards">
          <img src="https://images2.minutemediacdn.com/image/fetch/https%3A%2F%2Fgarnetandcocky.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2017%2F07%2F1192721601.jpeg" alt="" />
          <h1>Basketball</h1>
          <p>I`ve started playing basketball <br />
            when i was 12 years old</p>
        </div>

        <div className="cards">
          <img src="https://www.afisha.uz/uploads/media/2019/10/0017543.jpeg" alt="" />
          <h1>Karting</h1>
          <p>Karting is very interesting <br />
            hobbi and i love it</p>
        </div>

        <div className="cards">
          <img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/97/27/16/cinema-rex.jpg?w=1200&h=-1&s=1" alt="" />
          <h1>Movies</h1>
          <p>I`m interested in watching <br />
            movies, i watch it on my free time </p>
        </div>

        <div className="cards">
          <img src="https://www.hussle.com/blog/wp-content/uploads/2020/12/Gym-structure-1080x675.png" alt="" />
          <h1>Training</h1>
          <p>Everyday i wake up eraly<br />
            to train, it`s very useful</p>
        </div>

        <div className="cards">
          <img src="https://www.cpapracticeadvisor.com/wp-content/uploads/sites/2/2022/08/work-friends.jpg" alt="" />
          <h1>Meeting with my friends</h1>
          <p>My friends are really important<br />
            part of my life ,
            why we meeting ? |see below|</p>
        </div>

        <div className="cards">
          <img src="https://www.techspot.com/images2/news/bigimage/2015/06/2015-06-05-image.jpg" alt="" />
          <h1>Frontend & Backend</h1>
          <p>One of my skill is frontend developmend<br />
            I like making projects
          </p>
        </div>
      </div>
    </>
  );
}

export default Hobbi;
