import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

const Skill = () => {
    return (
        <>
            <Head>
                <title>My skills</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/profile.png" />
            </Head>






            <div className="nav_parent">
                <nav>
                    <div className="nav_left">
                        <Link href={"/"} ><h1>Saidolim Bakhodirov</h1></Link>
                    </div>
                    <div className="nav_right">
                        <Link href={"/Hobbi"} ><p className='nav_p1'>Hobbies</p></Link>
                        <Link href={"/About"} ><p>About </p></Link>
                    </div>
                </nav>
                <div className="nav_bottom">
                    <h1>Here are all of my skills</h1>
                    <p>Here you can find all  <br /> of my skills , go to next page below  </p>
                </div>
            </div>


            <div className="skill_parent">
                <div className="skill_top">
                    <h1>LANGUAGES</h1>
                </div>

                <div className="skill_bottom">

                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>English</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>C1 - Advanced</p>
                            </div>
                        </div>
                    </div>
                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>Russian</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>C2 - Proficiency</p>
                            </div>
                        </div>
                    </div>

                


                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>Uzbek</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>C2 - Proficiency</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>





<hr />



            <div className="skill_parent">
                <div className="skill_top">
                    <h1>Frontend knowlages</h1>
                </div>

                <div className="skill_bottom">

                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>HTML & CSS</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Experienced</p>
                            </div>
                        </div>
                    </div>
                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>JAVASCRIPT</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Skillful</p>
                            </div>
                        </div>
                    </div>

                


                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>REACT</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Skillful</p>
                            </div>
                        </div>
                    </div>


                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>Next</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Skillful</p>
                            </div>
                        </div>
                    </div>

                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>GIT & GITHUB</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Skillful</p>
                            </div>
                        </div>
                    </div>

                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>REDUX TOOLKIT</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Beginner</p>
                            </div>
                        </div>
                    </div>
                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>RTK QUERY</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Skillful</p>
                            </div>
                        </div>
                    </div>

                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>Bootswrap</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Experienced</p>
                            </div>
                        </div>
                    </div>



                </div>

                </div>

                   
                <hr />


                
                <div className="skill_parent">
                <div className="skill_top">
                    <h1>My own skills</h1>
                </div>

                <div className="skill_bottom">

                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>SMM</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>Advanced</p>
                            </div>
                        </div>
                    </div>
                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>P2P</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p>skillful</p>
                            </div>
                        </div>
                    </div>

                


                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>Buisbess</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p> Proficiency</p>
                            </div>
                        </div>
                    </div>

                    <div className="skill_card">
                        <div className="skill_card_top">
                            <h3>Dropship</h3>
                        </div>
                        <div className="skill_card_bottom">
                            <div className="skill_card_bottom_l">
                                <button></button>
                                <button></button>
                            </div>
                            <div className="skill_card_bottom_right">
                                <p> Beginner</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>




                  


            

        </>
    )
}

export default Skill